<?php
/**
 * FleetApiTest
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use OpenAPI\Client\Configuration;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FleetApiTest Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FleetApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createChart
     *
     * Create Chart.
     *
     */
    public function testCreateChart()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createShipShipScan
     *
     * Scan Ships.
     *
     */
    public function testCreateShipShipScan()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createShipSystemScan
     *
     * Scan Systems.
     *
     */
    public function testCreateShipSystemScan()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createShipWaypointScan
     *
     * Scan Waypoints.
     *
     */
    public function testCreateShipWaypointScan()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSurvey
     *
     * Create Survey.
     *
     */
    public function testCreateSurvey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dockShip
     *
     * Dock Ship.
     *
     */
    public function testDockShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for extractResources
     *
     * Extract Resources.
     *
     */
    public function testExtractResources()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for extractResourcesWithSurvey
     *
     * Extract Resources with Survey.
     *
     */
    public function testExtractResourcesWithSurvey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMounts
     *
     * Get Mounts.
     *
     */
    public function testGetMounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMyShip
     *
     * Get Ship.
     *
     */
    public function testGetMyShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMyShipCargo
     *
     * Get Ship Cargo.
     *
     */
    public function testGetMyShipCargo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMyShips
     *
     * List Ships.
     *
     */
    public function testGetMyShips()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRepairShip
     *
     * Get Repair Ship.
     *
     */
    public function testGetRepairShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getScrapShip
     *
     * Get Scrap Ship.
     *
     */
    public function testGetScrapShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShipCooldown
     *
     * Get Ship Cooldown.
     *
     */
    public function testGetShipCooldown()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getShipNav
     *
     * Get Ship Nav.
     *
     */
    public function testGetShipNav()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for installMount
     *
     * Install Mount.
     *
     */
    public function testInstallMount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for jettison
     *
     * Jettison Cargo.
     *
     */
    public function testJettison()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for jumpShip
     *
     * Jump Ship.
     *
     */
    public function testJumpShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for navigateShip
     *
     * Navigate Ship.
     *
     */
    public function testNavigateShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for negotiateContract
     *
     * Negotiate Contract.
     *
     */
    public function testNegotiateContract()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for orbitShip
     *
     * Orbit Ship.
     *
     */
    public function testOrbitShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchShipNav
     *
     * Patch Ship Nav.
     *
     */
    public function testPatchShipNav()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseCargo
     *
     * Purchase Cargo.
     *
     */
    public function testPurchaseCargo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for purchaseShip
     *
     * Purchase Ship.
     *
     */
    public function testPurchaseShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for refuelShip
     *
     * Refuel Ship.
     *
     */
    public function testRefuelShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeMount
     *
     * Remove Mount.
     *
     */
    public function testRemoveMount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for repairShip
     *
     * Repair Ship.
     *
     */
    public function testRepairShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scrapShip
     *
     * Scrap Ship.
     *
     */
    public function testScrapShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sellCargo
     *
     * Sell Cargo.
     *
     */
    public function testSellCargo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for shipRefine
     *
     * Ship Refine.
     *
     */
    public function testShipRefine()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for siphonResources
     *
     * Siphon Resources.
     *
     */
    public function testSiphonResources()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transferCargo
     *
     * Transfer Cargo.
     *
     */
    public function testTransferCargo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for warpShip
     *
     * Warp Ship.
     *
     */
    public function testWarpShip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
