<?php
/**
 * FactionTraitSymbol
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

/**
 * FactionTraitSymbol Class Doc Comment
 *
 * @description The unique identifier of the trait.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum FactionTraitSymbol: string
{
    case BUREAUCRATIC = 'BUREAUCRATIC';

    case SECRETIVE = 'SECRETIVE';

    case CAPITALISTIC = 'CAPITALISTIC';

    case INDUSTRIOUS = 'INDUSTRIOUS';

    case PEACEFUL = 'PEACEFUL';

    case DISTRUSTFUL = 'DISTRUSTFUL';

    case WELCOMING = 'WELCOMING';

    case SMUGGLERS = 'SMUGGLERS';

    case SCAVENGERS = 'SCAVENGERS';

    case REBELLIOUS = 'REBELLIOUS';

    case EXILES = 'EXILES';

    case PIRATES = 'PIRATES';

    case RAIDERS = 'RAIDERS';

    case CLAN = 'CLAN';

    case GUILD = 'GUILD';

    case DOMINION = 'DOMINION';

    case FRINGE = 'FRINGE';

    case FORSAKEN = 'FORSAKEN';

    case ISOLATED = 'ISOLATED';

    case LOCALIZED = 'LOCALIZED';

    case ESTABLISHED = 'ESTABLISHED';

    case NOTABLE = 'NOTABLE';

    case DOMINANT = 'DOMINANT';

    case INESCAPABLE = 'INESCAPABLE';

    case INNOVATIVE = 'INNOVATIVE';

    case BOLD = 'BOLD';

    case VISIONARY = 'VISIONARY';

    case CURIOUS = 'CURIOUS';

    case DARING = 'DARING';

    case EXPLORATORY = 'EXPLORATORY';

    case RESOURCEFUL = 'RESOURCEFUL';

    case FLEXIBLE = 'FLEXIBLE';

    case COOPERATIVE = 'COOPERATIVE';

    case UNITED = 'UNITED';

    case STRATEGIC = 'STRATEGIC';

    case INTELLIGENT = 'INTELLIGENT';

    case RESEARCH_FOCUSED = 'RESEARCH_FOCUSED';

    case COLLABORATIVE = 'COLLABORATIVE';

    case PROGRESSIVE = 'PROGRESSIVE';

    case MILITARISTIC = 'MILITARISTIC';

    case TECHNOLOGICALLY_ADVANCED = 'TECHNOLOGICALLY_ADVANCED';

    case AGGRESSIVE = 'AGGRESSIVE';

    case IMPERIALISTIC = 'IMPERIALISTIC';

    case TREASURE_HUNTERS = 'TREASURE_HUNTERS';

    case DEXTEROUS = 'DEXTEROUS';

    case UNPREDICTABLE = 'UNPREDICTABLE';

    case BRUTAL = 'BRUTAL';

    case FLEETING = 'FLEETING';

    case ADAPTABLE = 'ADAPTABLE';

    case SELF_SUFFICIENT = 'SELF_SUFFICIENT';

    case DEFENSIVE = 'DEFENSIVE';

    case PROUD = 'PROUD';

    case DIVERSE = 'DIVERSE';

    case INDEPENDENT = 'INDEPENDENT';

    case SELF_INTERESTED = 'SELF_INTERESTED';

    case FRAGMENTED = 'FRAGMENTED';

    case COMMERCIAL = 'COMMERCIAL';

    case FREE_MARKETS = 'FREE_MARKETS';

    case ENTREPRENEURIAL = 'ENTREPRENEURIAL';

}


