<?php
/**
 * WaypointTraitSymbol
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpaceTraders API
 *
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

/**
 * WaypointTraitSymbol Class Doc Comment
 *
 * @description The unique identifier of the trait.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum WaypointTraitSymbol: string
{
    case UNCHARTED = 'UNCHARTED';

    case UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION';

    case MARKETPLACE = 'MARKETPLACE';

    case SHIPYARD = 'SHIPYARD';

    case OUTPOST = 'OUTPOST';

    case SCATTERED_SETTLEMENTS = 'SCATTERED_SETTLEMENTS';

    case SPRAWLING_CITIES = 'SPRAWLING_CITIES';

    case MEGA_STRUCTURES = 'MEGA_STRUCTURES';

    case PIRATE_BASE = 'PIRATE_BASE';

    case OVERCROWDED = 'OVERCROWDED';

    case HIGH_TECH = 'HIGH_TECH';

    case CORRUPT = 'CORRUPT';

    case BUREAUCRATIC = 'BUREAUCRATIC';

    case TRADING_HUB = 'TRADING_HUB';

    case INDUSTRIAL = 'INDUSTRIAL';

    case BLACK_MARKET = 'BLACK_MARKET';

    case RESEARCH_FACILITY = 'RESEARCH_FACILITY';

    case MILITARY_BASE = 'MILITARY_BASE';

    case SURVEILLANCE_OUTPOST = 'SURVEILLANCE_OUTPOST';

    case EXPLORATION_OUTPOST = 'EXPLORATION_OUTPOST';

    case MINERAL_DEPOSITS = 'MINERAL_DEPOSITS';

    case COMMON_METAL_DEPOSITS = 'COMMON_METAL_DEPOSITS';

    case PRECIOUS_METAL_DEPOSITS = 'PRECIOUS_METAL_DEPOSITS';

    case RARE_METAL_DEPOSITS = 'RARE_METAL_DEPOSITS';

    case METHANE_POOLS = 'METHANE_POOLS';

    case ICE_CRYSTALS = 'ICE_CRYSTALS';

    case EXPLOSIVE_GASES = 'EXPLOSIVE_GASES';

    case STRONG_MAGNETOSPHERE = 'STRONG_MAGNETOSPHERE';

    case VIBRANT_AURORAS = 'VIBRANT_AURORAS';

    case SALT_FLATS = 'SALT_FLATS';

    case CANYONS = 'CANYONS';

    case PERPETUAL_DAYLIGHT = 'PERPETUAL_DAYLIGHT';

    case PERPETUAL_OVERCAST = 'PERPETUAL_OVERCAST';

    case DRY_SEABEDS = 'DRY_SEABEDS';

    case MAGMA_SEAS = 'MAGMA_SEAS';

    case SUPERVOLCANOES = 'SUPERVOLCANOES';

    case ASH_CLOUDS = 'ASH_CLOUDS';

    case VAST_RUINS = 'VAST_RUINS';

    case MUTATED_FLORA = 'MUTATED_FLORA';

    case TERRAFORMED = 'TERRAFORMED';

    case EXTREME_TEMPERATURES = 'EXTREME_TEMPERATURES';

    case EXTREME_PRESSURE = 'EXTREME_PRESSURE';

    case DIVERSE_LIFE = 'DIVERSE_LIFE';

    case SCARCE_LIFE = 'SCARCE_LIFE';

    case FOSSILS = 'FOSSILS';

    case WEAK_GRAVITY = 'WEAK_GRAVITY';

    case STRONG_GRAVITY = 'STRONG_GRAVITY';

    case CRUSHING_GRAVITY = 'CRUSHING_GRAVITY';

    case TOXIC_ATMOSPHERE = 'TOXIC_ATMOSPHERE';

    case CORROSIVE_ATMOSPHERE = 'CORROSIVE_ATMOSPHERE';

    case BREATHABLE_ATMOSPHERE = 'BREATHABLE_ATMOSPHERE';

    case THIN_ATMOSPHERE = 'THIN_ATMOSPHERE';

    case JOVIAN = 'JOVIAN';

    case ROCKY = 'ROCKY';

    case VOLCANIC = 'VOLCANIC';

    case FROZEN = 'FROZEN';

    case SWAMP = 'SWAMP';

    case BARREN = 'BARREN';

    case TEMPERATE = 'TEMPERATE';

    case JUNGLE = 'JUNGLE';

    case OCEAN = 'OCEAN';

    case RADIOACTIVE = 'RADIOACTIVE';

    case MICRO_GRAVITY_ANOMALIES = 'MICRO_GRAVITY_ANOMALIES';

    case DEBRIS_CLUSTER = 'DEBRIS_CLUSTER';

    case DEEP_CRATERS = 'DEEP_CRATERS';

    case SHALLOW_CRATERS = 'SHALLOW_CRATERS';

    case UNSTABLE_COMPOSITION = 'UNSTABLE_COMPOSITION';

    case HOLLOWED_INTERIOR = 'HOLLOWED_INTERIOR';

    case STRIPPED = 'STRIPPED';

}


